# Travis Build Integration
# https://docs.travis-ci.com
language: perl

before_install:
  - sudo apt-get update
  - sudo apt-get install -y naturaldocs
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto

script:
  - chmod +x tools/make_docs
  - mkdir pages
  - ./tools/make_docs
  - mv -v docs/ pages/
  - cp README.md pages/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: pages/
  on:
    branch: master