# Travis Build Integration
# https://docs.travis-ci.com
language: minimal

stages:
  - build
  - name: deploy_dev
    if: branch != master
  - name: deploy
    if: branch = master


jobs:
  include:
    - stage: build
    - script:
      - chmod +x tools/make_docs
      - chmod +x tools/install_nd
      - mkdir pages
      - ./tools/install_nd
      - ./tools/make_docs
      - cp README.md pages/
    - stage: deploy_dev
    - script:
      - mv -v ./docs ./docs_dev
    - stage: deploy
    - script:
      - mv -v docs/ pages/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: pages/